version: "2"
prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/TailorBrands/tailor-rubocop/master/rubocop.yml"
      path: ".rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-79
exclude_patterns:
  - spec/**/*
